Montar artefacto

diff --git a/jobs/maven/build-simple.yml b/jobs/maven/build-simple.yml
--- a/jobs/maven/build-simple.yml
+++ b/jobs/maven/build-simple.yml
@@ -14,6 +14,7 @@ build-job:
   rules:
     # Hacemos build solo en develop, master y hotfix (si lo hay)
     - if: $CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == $HOTFIX_BRANCH
+      when: always
 
   cache:
     paths:
@@ -35,28 +36,19 @@ build-job:
     # Si es master deberia ser release.
     #
     - |
-      [[ -d tmp_jars ]] && rm -f tmp_jars/*
-      retcode=0
       if [[ $CI_COMMIT_REF_NAME == "master" && $IS_SNAPSHOT == "true" ]]; then
-        echo -e "ERROR: PUSH de <master> en version SNAPSHOT no permitido.\nSe ha generado el artefacto en tmp_jars/, pero el pipeline se interrumpira." 
-        retcode=2
+        echo -e "ERROR: PUSH de <master> en version SNAPSHOT no permitido.\nSe ha generado el artefacto, pero el pipeline se interrumpira." 
+        exit 2
       fi
       if [[ $CI_COMMIT_REF_NAME == "develop" && $IS_SNAPSHOT != "true" && $ALLOW_RELEASE_IN_DEVELOP != "true" ]]; then
-        echo -e "ERROR: PUSH de <develop> en verion RELEASE no permitido.\nSe ha generado el artefacto en tmp_jars/, pero el pipeline se interrumpira."
-        retcode=3
+        echo -e "ERROR: PUSH de <develop> en verion RELEASE no permitido.\nSe ha generado el artefacto, pero el pipeline se interrumpira."
+        exit 3
       fi
-      if [[ $retcode > 0 ]]; then
-        mkdir -p tmp_jars
-        rm -f tmp_jars/*
-        cp target/*.jar tmp_jars
-        git config user.name "$CICD_USER"
-        git config user.email "$CICD_EMAIL"
-        git remote remove origin
-        git remote add origin ${ORIGIN_URL}
-        git add tmp_jars
-        git commit -m "Guardar tmp_jars/${PRJ_VERS}.jar"
-      fi
-      echo "Build finalizado con retcode: $retcode"
-    - exit $retcode
+      echo "Build finalizado con exito"
+
+  artifacts:
+    paths:
+      - ./target/*.jar
+    expire_in: 2 hours
 
   ################################## E O F ##########################################
