Seguimos con errorres tontos

diff --git a/jobs/maven/deploy-simple.yml b/jobs/maven/deploy-simple.yml
--- a/jobs/maven/deploy-simple.yml
+++ b/jobs/maven/deploy-simple.yml
@@ -61,10 +61,14 @@ deploy-job:
       # directorio del proyecto. Como en sftp el comando mkdir no tiene la opcion -p, hay que hacerlo
       # mediante ssh. Por contra, si estamos haciendo un update, eliminamos el directorio deploy anterior.
       #
-      COMANDO="( mkdir -p ${DEPLOY_SSH_PATH}; rm -Rf ${DEPLOY_SSH_PATH}/deploy )"
+      COMANDO="mkdir -p ${DEPLOY_SSH_PATH}; rm -Rf ${DEPLOY_SSH_PATH}/deploy"
       echo "INFO Ejecutando comando remoto ${COMANDO}.."
-      ssh -o StrictHostKeyChecking=no -i ${DEPLOY_SSH_KEY} ${CONN_STRING} "${COMANDO}"
-      [[ $? != 0 ]] && { echo "ERROR No se ha podido ejecutar"; exit 1; }
+      ssh -o StrictHostKeyChecking=no -i ${DEPLOY_SSH_KEY} ${CONN_STRING} "${COMANDO}" > prep.log
+      if [[ $? != 0 ]]; then
+        echo "ERROR No se ha podido ejecutar"
+        cat prep.log
+        exit 1
+      fi
       #
       # Preparamos el bat que vamos a ajecutar con sftp (es un pequeño archivo temporal)
       #
