Primera version de deploy

diff --git a/jobs/maven/deploy-simple.yml b/jobs/maven/deploy-simple.yml
--- a/jobs/maven/deploy-simple.yml
+++ b/jobs/maven/deploy-simple.yml
@@ -35,25 +35,36 @@ deploy-job:
       \nEjecutando etapa DEPLOY en $CI_COMMIT_REF_NAME
       \n=============================================================================================="
     # En todas las etapas manuales hacemos lo mismo
-    - '[[ ${SKIP} == "true" ]] && { echo "WARN: Ha entrado SKIP=true, asi que saltamos esta etapa."; exit 0; }'
-    - 'echo "DOCKER_PRJ: ${DOCKER_PRJ}"'
-    - 'echo "IMG_TAG: ${IMG_TAG}"'
-    - 'echo "TF_VM_IP: $TF_VM_IP"'
-    # Solo si es un proyecto Docker
-    - '[[ $DOCKER_PRJ != "true" ]] && { echo "WARN: No es un proyecto Docker. Esta etapa no se ejecuta."; exit 0; }'
-    # DEPLOY_SSH_USER y DEPLOY_SSH_KEY son valiables del proyecto, y TF_VM_IP nos la ha devuelto la etapa tf-apply
-    - '[[ -z $TF_VM_IP ]] && { echo "ERROR: No existe la variable TF_VM_IP. No se puede continuar con el deploy."; exit 1; }'
-    - >
+    '[[ ${SKIP} == "true" ]] && { echo "WARN: Ha entrado SKIP=true, asi que saltamos esta etapa."; exit 0; }'
+    - |
+      # DEBUG
+      echo "DOCKER_PRJ: ${DOCKER_PRJ}"
+      echo "IMG_TAG: ${IMG_TAG}"
+      echo "TF_VM_IP: $TF_VM_IP"
+      echo "TF_VAR_VM_NAME: $TF_VAR_VM_NAME"
+      echo "DEPLOY_SSH_PATH: ${DEPLOY_SSH_PATH}"
+      echo "DEPLOY_SSH_SVC_NAME: ${DEPLOY_SSH_SVC_NAME}"
+      # Solo si es un proyecto Docker
+      # COMENTADO PROVISIONALMENTE [[ $DOCKER_PRJ != "true" ]] && { echo "WARN: No es un proyecto Docker. Esta etapa no se ejecuta."; exit 0; }
+      # DEPLOY_SSH_USER y DEPLOY_SSH_KEY son valiables del proyecto, y TF_VM_IP nos la ha devuelto la etapa tf-apply
+      [[ -z $TF_VM_IP ]] && { echo "ERROR: No existe la variable TF_VM_IP. No se puede continuar con el deploy."; exit 1; }
+      # Preparamos el bat que vamos a ajecutar con sftp (es un archivo temporal)
+      echo "cd ${DEPLOY_SSH_PATH}" > sftp.bat
+      echo "rmdir deploy" >> sftp.bat
+      echo "put deploy" >> sftp.bat 
+      echo "chmod +x deploy/deploy.sh" >> sftp.bat 
+      # DEBUG
+      echo "INFO Ejecutando el siguiente sftp bat:"
+      cat sftp.bat
+      # Lanzar el sftp
       CONN_STRING="${DEPLOY_SSH_USER}@${TF_VM_IP}"
-      ssh -o StrictHostKeyChecking=no -i ${DEPLOY_SSH_KEY} ${CONN_STRING} "
-      #cd $DEPLOY_SSH_PATH &&
-      #docker-compose down &&
-      #echo 'services:' > docker-compose.override.yml &&
-      #echo '    ${DOCKER_SERVICE_NAME}:' >> docker-compose.override.yml &&
-      #echo '        image: ${IMG_TAG}' >> docker-compose.override.yml &&
-      #docker-compose up -d &&
-      docker ps
-      "
-
+      #sftp -o StrictHostKeyChecking=no -i ${DEPLOY_SSH_KEY} -b sftp.bat ${CONN_STRING}
+      sftp -i ${DEPLOY_SSH_KEY} -b sftp.bat ${CONN_STRING}
+      [[ $? != 0 ]] && { echo "ERROR sftp no se ha ejecutado correctamente"; exit 1; }
+      # Ejecutamos el comando remoto de deploy
+      REMOTE_CMD="${DEPLOY_SSH_PATH}/deploy/deploy.sh > ${DEPLOY_SSH_PATH}/deploy/deploy.log 2>&1"
+      #ssh -o StrictHostKeyChecking=no -i ${DEPLOY_SSH_KEY} ${CONN_STRING} \"${REMOTE_CMD}\"
+      # Nos bajamos el log y lo mostramos
+      # PENDIENTE
 ################################## E O F ##########################################    
 
