Limpiar variables duplicadas, corregir errores

diff --git a/jobs/maven/deploy-simple.yml b/jobs/maven/deploy-simple.yml
--- a/jobs/maven/deploy-simple.yml
+++ b/jobs/maven/deploy-simple.yml
@@ -36,8 +36,11 @@ deploy-job:
     # En todas las etapas manuales hacemos lo mismo
     - '[[ ${SKIP} == "true" ]] && { echo "WARN: Ha entrado SKIP=true, asi que saltamos esta etapa."; exit 0; }'
     - |
+      # PRUEBAS !!!!!!!!!!!!
+      [[ -z ${IMG_TAG} && ${DEBUG_CD} == 'true' ]] && IMG_TAG=registry2.comunytek.com/comunytek/selfweb/selfwebspringboot/snapshot:5.0.6-SNAPSHOT.006 
+
       # DEBUG
-      echo "DOCKER_PRJ         : ${DOCKER_PRJ}"
+      echo "IS_DOCKER_PRJ         : ${IS_DOCKER_PRJ}"
       echo "IMG_TAG            : ${IMG_TAG}"
       echo "TF_VM_IP           : $TF_VM_IP"
       echo "TF_VAR_VM_NAME     : $TF_VAR_VM_NAME"
@@ -46,11 +49,15 @@ deploy-job:
       #
       # Solo si es un proyecto Docker
       #
-      # PROVISIONAL!!!!! [[ $DOCKER_PRJ != "true" ]] && { echo "WARN: No es un proyecto Docker. Esta etapa no se ejecuta."; exit 0; }
+      [[ -f Dockerfile ]] || { echo "WARN: No es un proyecto Docker. Esta etapa no se ejecuta."; exit 0; }
       #
       # DEPLOY_SSH_USER y DEPLOY_SSH_KEY son valiables del proyecto, y TF_VM_IP nos la ha devuelto la etapa tf-apply
       #
       [[ -z $TF_VM_IP ]] && { echo "ERROR: No existe la variable TF_VM_IP. No se puede continuar con el deploy."; exit 1; }
+      #
+      # IMG_TAG es una variable de entorno generada en la etapa 'docker'. Si no existe, hay algo mal.
+      #
+      [[ -z $IMG_TAG ]] && { echo "ERROR: No existe la variable IMG_TAG. Parece que no se ha ejecutado la etapa 'docker'"; exit 1; }
       #
       # Cadena de conexion a la VM que acabamos de provisionar
       #
@@ -82,8 +89,6 @@ deploy-job:
       #
       # Ejecutamos el comando de deploy
       #
-      # PRUEBAS!!!!
-      IMG_TAG=registry2.comunytek.com/comunytek/selfweb/selfwebspringboot/snapshot:5.0.6-SNAPSHOT.006
       COMANDO="${DEPLOY_SSH_PATH}/deploy/deploy.sh \
       -s ${DEPLOY_SSH_SVC_NAME} \
       -i ${IMG_TAG} \
