Ifs complicados

diff --git a/jobs/maven/docker-simple.yml b/jobs/maven/docker-simple.yml
--- a/jobs/maven/docker-simple.yml
+++ b/jobs/maven/docker-simple.yml
@@ -32,38 +32,54 @@ docker-register-job:
     # Solo si es un proyecto Docker
     - '[[ $DOCKER_PRJ != "true" ]] && { echo "WARN: No existe Dockerfile. Esta etapa no se ejecuta."; exit 0; }'
     #
-    # Si es develop deberia ser un snapshot.
-    # Si es master deberia ser release.
+    # Preparamos tagid. Las reglas actuales son:
+    #   - En <master> no se admite SNAPSHOT. Se registra en 'release' con el Id del proyecto.
+    #   - En <develop> se admite RELEASE solo si el flag ALLOW_RELEASE_IN_SNAPSHOT esta a true. Se registra en 'snapshot'
+    #     o 'relesae', pero agregando el SNAPSHOT_NUMBER, si existe.
+    #   - En rama hotfix se registra en 'hotfix' agregando el HOTFIX_NUMBER, si existe.
     #
-    - >
-      [[ $CI_COMMIT_REF_NAME == "develop" && $IS_SNAPSHOT != "true" && $ALLOW_RELEASE_IN_DEVELOP != "true" ]] &&
-      { echo -e "ERROR: PUSH de <develop> en verion RELEASE.";
-      exit 2; }
-    - >
-      [[ $CI_COMMIT_REF_NAME == "master" && $IS_SNAPSHOT == "true" && $ALLOW_SNAPSHOT_IN_MASTER != "true" ]] &&
-      { echo -e "ERROR: PUSH de <master> en version SNAPSHOT.";
-      exit 2; }
-    #
-    # Preparamos tagid. Si es release, al registry 'release' y solo con la version del proyecto (no se puede repetir)
-    #
-    - IMG_TAG="${CI_REGISTRY_IMAGE}/release:${PRJ_VERS}"
-    # Si es snapshot, al registry 'snapshot' y solo con la version del proyecto (no se puede repetir),
-    # salvo que nos definan un numero de snapshot adicional a la version.
-    # Si es hotfix, al registry 'hotfix' y solo con la version del proyecto (no se puede repetir),
-    # salvo que nos definan un numero de hotfix adicional a la version.
     - |
-      if [[ ${IS_SNAPSHOT} == "true" ]]; then
-          echo "DEBUG: Es snapshot numero $SNAPSHOT_NUMBER"
-          IMG_TAG="${CI_REGISTRY_IMAGE}/snapshot:${PRJ_VERS}"
-          if [[ ${SNAPSHOT_NUMBER} > "" ]]; then
-              IMG_TAG="${IMG_TAG}-${SNAPSHOT_NUMBER}""
+      IMG_TAG="${CI_REGISTRY_IMAGE}/wrong:${PRJ_VERS}"
+      if [[ ${CI_COMMIT_REF_NAME} == "master" ]]; then
+          if [[ $IS_SNAPSHOT == "true" ]]; then
+              echo -e "ERROR: PUSH de <master> en version SNAPSHOT no permitido"
+              exit 2
           fi
+          #
+          # Va al registry 'release' y solo con la version del proyecto.
+          #
+          IMG_TAG="${CI_REGISTRY_IMAGE}/release:${PRJ_VERS}"
+      elif [[ ${CI_COMMIT_REF_NAME} == "develop" ]]; then
+          if [[ $IS_SNAPSHOT == "true" ]]; then
+              #
+              # Va a 'snapshot'
+              #
+              IMG_TAG="${CI_REGISTRY_IMAGE}/snapshot:${PRJ_VERS}"
+          else
+              if [[ $ALLOW_SNAPSHOT_IN_MASTER != "true"]]; then
+                echo -e "ERROR: PUSH de <develop> en version RELEASE no permitido"
+                exit 2
+              fi
+              #
+              # Va a 'release'
+              #
+              IMG_TAG="${CI_REGISTRY_IMAGE}/release:${PRJ_VERS}"
+          fi
+          #
+          # Sea snapshot o release, en develop siempre agregamos el numero de snapshot, si existe
+          #
+          [[ $SNAPSHOT_NUMBER > "" ]] && IMG_TAG="${IMG_TAG}-${SNAPSHOT_NUMBER}"
       elif [[ ${CI_COMMIT_REF_NAME} == ${HOTFIX_BRANCH} ]]; then
-          echo "DEBUG: Es hotfix numero $HOTFIX_NUMBER"
+          #
+          # Va a 'hotfix'
+          #
           IMG_TAG="${CI_REGISTRY_IMAGE}/hotfix:${PRJ_VERS}"
           if [[ ${HOTFIX_NUMBER} > "" ]]; then
               IMG_TAG="${IMG_TAG}-${HOTFIX_NUMBER}"
           fi
+      else
+          echo "ERROR: Rama ${CI_COMMIT_REF_NAME} no puede pasar etapa Docker"
+          exit 2          
       fi
     - 'echo "IMG_TAG: ${IMG_TAG}"'
     - docker -v
