Ultima prueba

diff --git a/jobs/maven/register-simple.yml b/jobs/maven/register-simple.yml
--- a/jobs/maven/register-simple.yml
+++ b/jobs/maven/register-simple.yml
@@ -35,12 +35,11 @@ pkg-register-job:
     # Si ademas queremos guardar los fuentes, lo hacemos algo mas complicado:
     #
     - |
-      JAR_FILE="./target/${PRJ_NAME}-${PRJ_VERS}.jar"
+      ORIGID="${PRJ_NAME}-${PRJ_VERS}"
+      ARTID="${ARTID}"
+      JAR_FILE="./target/${ORIGID}.jar"
       [[ -f "${JAR_FILE}" ]] || { echo "El archivo ${JAR_FILE} no existe"; exit 1; }
       REG_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven"
-      VERSION="${PRJ_VERS}"
-      SRC_FILE="src-${PRJ_VERS}.jar"
-      jar cf ${SRC_FILE} ./src/*
       #
       # En que rama estamos?
       #
@@ -56,38 +55,44 @@ pkg-register-job:
                   #
                   # Agregamos numero de snapshot, si lo hay
                   #
-                  [[ -z $SNAPSHOT_NUMBER ]] || VERSION="${VERSION}-${SNAPSHOT_NUMBER}"
+                  [[ -z $SNAPSHOT_NUMBER ]] || ARTID="${ARTID}-${SNAPSHOT_NUMBER}"
               else
                   if [[ $ALLOW_RELEASE_IN_DEVELOP != "true" ]]; then
-                    echo "ERROR: PUSH de <develop> en version RELEASE no permitido"
-                    exit 2
+                      echo "ERROR: PUSH de <develop> en version RELEASE no permitido"
+                      exit 2
                   fi
                   #
                   # Le agregamos "-DEV"
                   #
-                  VERSION="${VERSION}-DEV"
+                  ARTID="${ARTID}-DEV"
                   #
                   # Agregamos numero de snapshot, si lo hay
                   #
-                  [[ -z $SNAPSHOT_NUMBER ]] || VERSION="${VERSION}-${SNAPSHOT_NUMBER}"
+                  [[ -z $SNAPSHOT_NUMBER ]] || ARTID="${ARTID}-${SNAPSHOT_NUMBER}"
               fi
               ;;
           ${HOTFIX_BRANCH})
               #
               # Agregamos "-HOTFIX"
               #
-              VERSION="${VERSION}-HOTFIX"
-              [[ -z $HOTFIX_NUMBER ]] || VERSION="${VERSION}-${HOTFIX_NUMBER}"
+              ARTID="${ARTID}-HOTFIX"
+              [[ -z $HOTFIX_NUMBER ]] || ARTID="${ARTID}-${HOTFIX_NUMBER}"
               ;;
           *)
               echo "ERROR: Rama ${CI_COMMIT_REF_NAME} no puede pasar etapa Register"
               exit 2          
               ;;
       esac
+      if [[ $ARTID != $ORIGID ]]; then
+          mv ${JAR_FILE} "./target/${ARTID}.jar"
+          JAR_FILE="./target/${ARTID}.jar"
+      fi
+      SRC_FILE="src-${ARTID}.jar"
+      jar cf ${SRC_FILE} ./src/*
       #
       # Deploy
       #
-      mvn deploy:deploy-file -s ci_settings.xml -Durl="${REG_URL}" -Dversion="${VERSION}" \
+      mvn deploy:deploy-file -s ci_settings.xml -Durl="${REG_URL}" \
       -DrepositoryId="gitlab-maven" -Dfile="${JAR_FILE}" -DpomFile="pom.xml" -Dsources="${SRC_FILE}"
   
   ################################## E O F ##########################################
