Agregar etapa Tag

diff --git a/jobs/maven/tag-simple.yml b/jobs/maven/tag-simple.yml
--- a/jobs/maven/tag-simple.yml
+++ b/jobs/maven/tag-simple.yml
@@ -1,5 +1,5 @@
 #########################################################################################################
-# Crear un tag, solo para master. Por el momento manual
+# Crear un tag. Por el momento manual
 #
 # Vers  Por Fecha      Notas
 # ----- --- ---------- ----------------------------------------------------------------------------------
@@ -13,13 +13,7 @@ tag-job:
     SEGUIR: "false"
 
   rules:
-    # Hacemos tag en master solo si es release
-    - if: $CI_COMMIT_REF_NAME == "master" && $IS_SNAPSHOT != "true"
-    # Hacemos tag en develop solo si es SNAPSHOT, y solo manual
-    - if: $CI_COMMIT_REF_NAME == "develop" && $IS_SNAPSHOT == "true"
-      when: manual
-    # Excepcionalmente hacemos tag en una rama concreta, pero solo de forma manual
-    - if: $CI_COMMIT_REF_NAME == $HOTFIX_BRANCH
+    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == $HOTFIX_BRANCH
       when: manual
 
   cache:
@@ -31,14 +25,58 @@ tag-job:
       echo -e "==============================================================================================
       \nEjecutando etapa TAG en $CI_COMMIT_REF_NAME
       \n=============================================================================================="
-    # Si no es master, debe entrar SEGUIR=true
-    - '[[ $CI_COMMIT_REF_NAME != "master" && $SEGUIR != "true" ]] && { echo "ERROR: Para ejecutar este job debe establecer la variable SEGUIR a true"; exit 1; }'
-    - 'TAG="${CI_COMMIT_REF_NAME}-${PRJ_VERS}"'
-    - '[[ $CI_COMMIT_REF_NAME == $HOTFIX_BRANCH && $HOTFIX_NUMBER > "" ]] && TAG=${TAG}-${HOTFIX_NUMBER}'
+    # Para continuar, debe entrar SEGUIR=true
+    - '[[ $SEGUIR != "true" ]] && { echo "WARN: Para ejecutar este job debe establecer la variable SEGUIR a true"; exit 1; }'
+    #
+    #  Aplicar reglas complejas
+    #
+    - |
+      TAG="wrong-${PRJ_VERS}"
+      if [[ ${CI_COMMIT_REF_NAME} == "master" ]]; then
+          if [[ $IS_SNAPSHOT == "true" ]]; then
+              echo -e "ERROR: PUSH de <master> en version SNAPSHOT no permitido"
+              exit 2
+          fi
+          #
+          # A 'release' y solo con la version del proyecto.
+          #
+          TAG="release-${PRJ_VERS}"
+      elif [[ ${CI_COMMIT_REF_NAME} == "develop" ]]; then
+          if [[ $IS_SNAPSHOT == "true" ]]; then
+              #
+              # Va a 'snapshot'
+              #
+              TAG="snapshot-${PRJ_VERS}"
+          else
+              if [[ $ALLOW_RELEASE_IN_DEVELOP != "true"]]; then
+                echo -e "ERROR: PUSH de <develop> en version RELEASE no permitido"
+                exit 2
+              fi
+              #
+              # Va a 'develop-release'
+              #
+              TAG="develop-release-${PRJ_VERS}"
+          fi
+          #
+          # Sea snapshot o release, en develop siempre agregamos el numero de snapshot, si existe
+          #
+          [[ -z $SNAPSHOT_NUMBER ]] || TAG="${TAG}.${SNAPSHOT_NUMBER}"
+      elif [[ ${CI_COMMIT_REF_NAME} == ${HOTFIX_BRANCH} ]]; then
+          #
+          # Va a 'hotfix'
+          #
+          TAG="hotfix-${PRJ_VERS}"
+          [[ -z ${HOTFIX_NUMBER} ]] || TAG="${TAG}.${HOTFIX_NUMBER}"
+      else
+          echo "ERROR: Rama ${CI_COMMIT_REF_NAME} no puede pasar etapa Tag"
+          exit 2          
+      fi
     - 'echo "Creando tag $TAG en ORIGIN_URL: ${ORIGIN_URL}"'
     - git config user.name "$CICD_USER"
     - git config user.email "$CICD_EMAIL"
     - git remote remove origin
     - git remote add origin ${ORIGIN_URL}
     - git tag -a $TAG -m "Build $TAG"
-    - git push --tags
+    - git push origin $TAG
+
+################################## E O F ##########################################    
